server:
  port: 8000
  netty:
    # Boost Netty IO threads to handle thousands of concurrent sockets
    connection-timeout: 3000ms
    idle-timeout: 10s

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 500ms # Fast timeout so Redis never blocks Gateway execution
      lettuce:
        pool:
          max-active: 100
          max-idle: 20

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
            allowedHeaders: "*"
            allowCredentials: true

      # Apply JWT validation globally once
      default-filters:
        - JwtAuthenticationFilter
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        - RemoveResponseHeader=Content-Security-Policy

      routes:
        # Route 1: Auth & Public
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/public/**, /api/v1/auth/**, /api/v1/users/**, /api/v1/profiles/**

        # Route 2: Catalog Service (Now with User-Based Rate Limiting)
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/v1/catalog/**, /api/v1/titles/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 100
#                redis-rate-limiter.burstCapacity: 200
#                key-resolver: "#{@userKeyResolver}"

        # Route 3: Streaming Service
        - id: streaming-service
          uri: lb://STREAMING-SERVICE
          predicates:
            - Path=/api/v1/stream/**, /api/v1/progress/**

        # Route 4: Payments
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**

jwt:
  secret: TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$VTaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/